# Generated by Django 4.2 on 2023-04-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=25)),
                ('year', models.IntegerField(max_length=4)),
                ('image', models.CharField(max_length=10000)),
            ],
        ),
    ]
