# Generated by Django 4.2 on 2023-04-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('image', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(),
        ),
    ]
