# Generated by Django 4.2 on 2023-04-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MR', '0002_top_movies_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='averageRating',
            field=models.CharField(default=5.5, max_length=10),
            preserve_default=False,
        ),
    ]
