# Generated by Django 4.2 on 2023-04-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MR', '0003_movie_averagerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_movies',
            name='averageRating',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
